[package]
name = "mig"
version = "0.1.0"
authors = ["Anton Barkovsky <anton@swarmer.me>"]

[dependencies]
byteorder = "1.0"
cast = "0.2"
docopt = "0.6"
env_logger = "0.3"
log = "0.3"
rand = "0.3"
rustc-serialize = "0.3"
